# Cargo.toml
[package]
name = "demo-lib"
version = "0.1.0"
authors = ["Cédric Champeau <cedric.champeau+nospam@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
md-5 = "0.9.1"