/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.8.2/userguide/multi_project_builds.html
 */

rootProject.name = "gradle-wasm-plugin"

// build-logic
includeBuild("build-logic")

// subprojects
include("wasmer-utils")
include("wasm-gradle-annotations")
include("wasm-gradle-processor")
include("wasm-base-tasks")
include("rust-lib")
include("plugin")

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    setUrl("https://dl.bintray.com/wasmer/wasmer-jni/")
                }
            }
            filter {
                includeGroup("org.wasmer")
            }
        }
    }
}